### ISSUE TITLE
v0.2.0 builds err due to private variable leak

### ISSUE THREAD

**Issue by goshlanguage** [khonsulabs/cushy#141]
Hi team,

Thanks for your hard work on this project, I'm excited to explore it.

I'm trying to run/build the [button example](https://github.com/khonsulabs/cushy/blob/main/examples/basic-button.rs) in the `README` and I'm running into a build time error about a private  var being leaked via a public interface. I've added cushy via `cargo add`:

```sh
$ cargo add cushy      
    Updating crates.io index
      Adding cushy v0.2.0 to dependencies.
      
$ cargo run 
   Compiling cushy v0.2.0
error[E0446]: crate-private type `InvalidationStatus` in public interface
    --> /Users/ryan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cushy-0.2.0/src/window.rs:1418:9
     |
1418 |         pub redraw_status: InvalidationStatus,
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak crate-private type
     |
    ::: /Users/ryan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cushy-0.2.0/src/context.rs:1258:1
     |
1258 | pub(crate) struct InvalidationStatus {
     | ------------------------------------ `InvalidationStatus` declared as crate-private

For more information about this error, try `rustc --explain E0446`.
error: could not compile `cushy` (lib) due to previous error      
```

Am I missing a dependency or is this error legitimate?

Thanks for your help

**Comment by ecton** [comment]
Sorry for the issues you're having! The issue is that Rust 1.73 and prior report this error, but it's not an error in 1.74 or later. This is already fixed on the main branch. There are two ways to solve this today:

- Update Rust (if you're willing/able).
- Try using the `main` branch on git instead of v0.2.0

I'll be releasing v0.3 soon, hopefully in a week or so.

**Comment by goshlanguage** [comment]
Thanks! Upgraded my rust version and now I'm running the examples, no problem!
