### ISSUE TITLE
Padding inconsistency in `containers` example

### ISSUE THREAD

**Issue by bluenote10** [khonsulabs/cushy#158]
I've noticed a minor padding/spacing inconsistency in the `containers` example:

![image](https://github.com/khonsulabs/cushy/assets/3620703/f8ff7805-22d7-42ef-870a-6e182a9c84ee)

The implementation would suggest that the "Mid" container should probably have the same right-padding inside "Low" as the other containers, especially since it is the case in the recursive versions of the function.

**Comment by ecton** [comment]
Thank you for reporting this! I'm almost 100% certain I know what I did to cause this, as I thought to myself, "this will probably break the container shadow calculation," but I somehow didn't notice this when testing the change!
