### ISSUE TITLE
Add monitor/display access through App

### ISSUE THREAD

**Issue by ecton** [khonsulabs/cushy#163]
Some applications need to be able to position windows precisely, and Cushy/Kludgine maintain access to the monitor information that Winit provides.

Monitor information is technically available through winit's `WIndow` in addition to the event loop, but it seems more correct to provide an API in Cushy that attaches the information to the `App` type than it does to add it to `WindowHandle`.

This almost certainly is going to require changes in Kludgine since it hides winits event loop IIRC.

**Comment by andersonsilva87** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
