### ISSUE TITLE
Internationalization/localization support

### ISSUE THREAD

**Issue by hydra** [khonsulabs/cushy#187]
I couldn't find any examples or code related to internationalization. Ideally I'd like to be able to change the language of the application at run-time and have the language change reflected immediately, in the same way that Vizia does.

Do you have plans to support internationalization/localization?

**Comment by ecton** [comment]
Yes I plan on adding Fluent integration and making it as easy as possible to use, and switching languages should be reactive just like dark/light mode switching is.

**Comment by ecton** [comment]
This has been addressed by @hydra  and myself in #226.
