### ISSUE TITLE
Semantics of exact size vs lower bounded size?

### ISSUE THREAD

**Issue by bluenote10** [khonsulabs/cushy#197]
Another small example where I'm unsure if this is intended behavior or a minor bug. It is about the usage of an exact size like `.width(Px::new(100))` vs a lower bounded size like `.width(Px::new(100)..)`. Consider the following example:

```rust
use cushy::animation::ZeroToOne;
use cushy::figures::units::Px;
use cushy::figures::Zero;
use cushy::value::Dynamic;
use cushy::widget::MakeWidget;
use cushy::widgets::progress::Progressable;
use cushy::Run;

fn content() -> impl MakeWidget {
    let progress = Dynamic::new(ZeroToOne::ZERO);
    progress
        .clone()
        .progress_bar()
        .width(Px::new(100)..) // using just `Px::new(100)` works
        .contain()
        .centered()
        .expand()
}

pub fn main() -> cushy::Result<()> {
    content().run()
}
```

Using an exact size, the widget renders as:

![image](https://github.com/user-attachments/assets/eb062b54-a5d3-4192-9549-6766f2d38e4f)

Using a lower bounded size, the widget renders as:

![image](https://github.com/user-attachments/assets/dbf129da-fb5d-493e-ba0f-542077ad3315)

For some reason, the progress bar got shrunken down to less then the 100 pixels in this case. Intuitively I would have expected that the range syntax would express _100 pixel or more_, so I'm a bit surprised that it can shrink now. Interestingly, it still has a width of 100 to the outside (barely visible by the container size) -- only the inner widget seems to have lost its minimum width constraint?

**Comment by ecton** [comment]
Thank you for reporting this! This looks like it only affected the `Slider` widget, which is what the progress bar uses under the hood.
