### ISSUE TITLE
Add DropDown widget

### ISSUE THREAD

**Issue by hydra** [khonsulabs/cushy#205]
This is a much-needed widget.  in HTML this is a 'Select' with 'Option's.

For the value type, an implementation should use a `Dynamic<Option<T>>` or something, not just a `Dynamic<T>` so that it's possible to display a drop-down widget where no selection has been made.

Examples: https://www.google.com/search?&q=dropdown&udm=2

#153 (ComboBox) mentioins ListBox but I couldn't find any implementation of DropDown or ListBox in Cushy right now.

In my example I had to use a set of Radio buttons instead, which wasn't ideal and doesn't scale where there is a reasonable number of items to choose from.

**Comment by ecton** [comment]
This widget was already requested in #154. I agree it's an incredibly important widget.

**Comment by ecton** [comment]
> unusual name for it.

It's not really unusual. Dropdown makes less sense, given that the menu doesn't always drop *down*. The menu that appears always is "above" or "up" from the thing that shows it regardless of the menu positioning, so the pop-up terminology fits better. Additionally, Qt, Mac, and iOS all use this term to describe this widget, and WPF on Windows doesn't offer this type of widget (ComboBox serves this purpose in that framework).

From my initial research when creating the issue originally, popup button seemed like the better name. I made the mistake of not mentioning what it was also called in other frameworks when creating the issue. Sorry for the wasted time!

**Comment by hydra** [comment]
Good point regarding the positioning of the menu that appears when clicked.  I guess I'm remembering frameworks where the menu does always appear below the control where the name would make more sense.
