### ISSUE TITLE
Running Examples -- Compile Error

### ISSUE THREAD

**Issue by saturn77** [khonsulabs/cushy#228]
In the process of learning cushy, I cannot get the examples to compile and run as shown below. 

The trait bound `Unit: figures::Round` is not satisfied, and this is the error on several examples attempted. 

Using Rust Version 1.83.0. 

It may be helpful to have a very brief README in the examples section on minimum supported Rust version, how to run the examples, etc. 

![image](https://github.com/user-attachments/assets/b2233ebf-80d0-4582-980f-1384875de224)

**Comment by ecton** [comment]
The examples in the main branch should compile with the main branch. If you are trying a specific version of Cushy, try using the examples from the git tag for that version.

**Comment by saturn77** [comment]
Okay, thanks. I was using the main branch when I ran into the issue. I will try running on another computer just as a reference.
